/*
 * generated by Xtext 2.20.0
 */
package org.xtext.r2ps.rml.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class RMLUiModule extends AbstractRMLUiModule {

	public RMLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
