/*
 * generated by Xtext 2.20.0
 */
package org.xtext.r2ps.rml.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.r2ps.rml.RMLRuntimeModule;
import org.xtext.r2ps.rml.RMLStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class RMLIdeSetup extends RMLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new RMLRuntimeModule(), new RMLIdeModule()));
	}
	
}
