/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.rml.iRML;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.rml.iRML.IRMLFactory
 * @model kind="package"
 * @generated
 */
public interface IRMLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "iRML";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/rml/IRML";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "iRML";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  IRMLPackage eINSTANCE = org.xtext.example.rml.iRML.impl.IRMLPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.rml.iRML.impl.MappingImpl <em>Mapping</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.rml.iRML.impl.MappingImpl
   * @see org.xtext.example.rml.iRML.impl.IRMLPackageImpl#getMapping()
   * @generated
   */
  int MAPPING = 0;

  /**
   * The feature id for the '<em><b>Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAPPING__STATEMENTS = 0;

  /**
   * The number of structural features of the '<em>Mapping</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAPPING_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.rml.iRML.impl.StatementImpl <em>Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.rml.iRML.impl.StatementImpl
   * @see org.xtext.example.rml.iRML.impl.IRMLPackageImpl#getStatement()
   * @generated
   */
  int STATEMENT = 1;

  /**
   * The feature id for the '<em><b>Directive</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT__DIRECTIVE = 0;

  /**
   * The feature id for the '<em><b>Triple</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT__TRIPLE = 1;

  /**
   * The number of structural features of the '<em>Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.rml.iRML.impl.DirectiveImpl <em>Directive</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.rml.iRML.impl.DirectiveImpl
   * @see org.xtext.example.rml.iRML.impl.IRMLPackageImpl#getDirective()
   * @generated
   */
  int DIRECTIVE = 2;

  /**
   * The feature id for the '<em><b>Prefix</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIRECTIVE__PREFIX = 0;

  /**
   * The feature id for the '<em><b>Base</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIRECTIVE__BASE = 1;

  /**
   * The number of structural features of the '<em>Directive</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIRECTIVE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.rml.iRML.impl.PrefixIDImpl <em>Prefix ID</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.rml.iRML.impl.PrefixIDImpl
   * @see org.xtext.example.rml.iRML.impl.IRMLPackageImpl#getPrefixID()
   * @generated
   */
  int PREFIX_ID = 3;

  /**
   * The feature id for the '<em><b>Prefix Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREFIX_ID__PREFIX_NAME = 0;

  /**
   * The feature id for the '<em><b>Uri Ref</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREFIX_ID__URI_REF = 1;

  /**
   * The number of structural features of the '<em>Prefix ID</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREFIX_ID_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.rml.iRML.impl.BaseImpl <em>Base</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.rml.iRML.impl.BaseImpl
   * @see org.xtext.example.rml.iRML.impl.IRMLPackageImpl#getBase()
   * @generated
   */
  int BASE = 4;

  /**
   * The feature id for the '<em><b>Uri Ref</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BASE__URI_REF = 0;

  /**
   * The number of structural features of the '<em>Base</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BASE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.rml.iRML.impl.TriplesImpl <em>Triples</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.rml.iRML.impl.TriplesImpl
   * @see org.xtext.example.rml.iRML.impl.IRMLPackageImpl#getTriples()
   * @generated
   */
  int TRIPLES = 5;

  /**
   * The feature id for the '<em><b>Subject</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIPLES__SUBJECT = 0;

  /**
   * The feature id for the '<em><b>Predicate Object List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIPLES__PREDICATE_OBJECT_LIST = 1;

  /**
   * The number of structural features of the '<em>Triples</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIPLES_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.rml.iRML.impl.PredicateObjectImpl <em>Predicate Object</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.rml.iRML.impl.PredicateObjectImpl
   * @see org.xtext.example.rml.iRML.impl.IRMLPackageImpl#getPredicateObject()
   * @generated
   */
  int PREDICATE_OBJECT = 6;

  /**
   * The feature id for the '<em><b>Verb</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICATE_OBJECT__VERB = 0;

  /**
   * The feature id for the '<em><b>Object List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICATE_OBJECT__OBJECT_LIST = 1;

  /**
   * The number of structural features of the '<em>Predicate Object</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICATE_OBJECT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.rml.iRML.impl.PredicateObjectListImpl <em>Predicate Object List</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.rml.iRML.impl.PredicateObjectListImpl
   * @see org.xtext.example.rml.iRML.impl.IRMLPackageImpl#getPredicateObjectList()
   * @generated
   */
  int PREDICATE_OBJECT_LIST = 7;

  /**
   * The feature id for the '<em><b>Predicate Objects</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICATE_OBJECT_LIST__PREDICATE_OBJECTS = 0;

  /**
   * The number of structural features of the '<em>Predicate Object List</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICATE_OBJECT_LIST_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.rml.iRML.impl.ObjectListImpl <em>Object List</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.rml.iRML.impl.ObjectListImpl
   * @see org.xtext.example.rml.iRML.impl.IRMLPackageImpl#getObjectList()
   * @generated
   */
  int OBJECT_LIST = 8;

  /**
   * The feature id for the '<em><b>Objects</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT_LIST__OBJECTS = 0;

  /**
   * The number of structural features of the '<em>Object List</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT_LIST_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.rml.iRML.impl.VerbImpl <em>Verb</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.rml.iRML.impl.VerbImpl
   * @see org.xtext.example.rml.iRML.impl.IRMLPackageImpl#getVerb()
   * @generated
   */
  int VERB = 9;

  /**
   * The feature id for the '<em><b>Predicate</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERB__PREDICATE = 0;

  /**
   * The feature id for the '<em><b>Is A</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERB__IS_A = 1;

  /**
   * The number of structural features of the '<em>Verb</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERB_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.rml.iRML.impl.SubjectImpl <em>Subject</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.rml.iRML.impl.SubjectImpl
   * @see org.xtext.example.rml.iRML.impl.IRMLPackageImpl#getSubject()
   * @generated
   */
  int SUBJECT = 10;

  /**
   * The feature id for the '<em><b>Resource</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUBJECT__RESOURCE = 0;

  /**
   * The feature id for the '<em><b>Blank</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUBJECT__BLANK = 1;

  /**
   * The number of structural features of the '<em>Subject</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUBJECT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.rml.iRML.impl.iResourceImpl <em>iResource</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.rml.iRML.impl.iResourceImpl
   * @see org.xtext.example.rml.iRML.impl.IRMLPackageImpl#getiResource()
   * @generated
   */
  int IRESOURCE = 11;

  /**
   * The feature id for the '<em><b>Uri Ref</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IRESOURCE__URI_REF = 0;

  /**
   * The feature id for the '<em><b>Qname</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IRESOURCE__QNAME = 1;

  /**
   * The number of structural features of the '<em>iResource</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IRESOURCE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.rml.iRML.impl.ObjectImpl <em>Object</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.rml.iRML.impl.ObjectImpl
   * @see org.xtext.example.rml.iRML.impl.IRMLPackageImpl#getObject()
   * @generated
   */
  int OBJECT = 12;

  /**
   * The feature id for the '<em><b>Resource</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT__RESOURCE = 0;

  /**
   * The feature id for the '<em><b>Blank</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT__BLANK = 1;

  /**
   * The feature id for the '<em><b>Literal</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT__LITERAL = 2;

  /**
   * The number of structural features of the '<em>Object</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.rml.iRML.impl.LanguageStringImpl <em>Language String</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.rml.iRML.impl.LanguageStringImpl
   * @see org.xtext.example.rml.iRML.impl.IRMLPackageImpl#getLanguageString()
   * @generated
   */
  int LANGUAGE_STRING = 13;

  /**
   * The feature id for the '<em><b>Qutoed String</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LANGUAGE_STRING__QUTOED_STRING = 0;

  /**
   * The feature id for the '<em><b>Lang</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LANGUAGE_STRING__LANG = 1;

  /**
   * The number of structural features of the '<em>Language String</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LANGUAGE_STRING_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.rml.iRML.impl.LiteralImpl <em>Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.rml.iRML.impl.LiteralImpl
   * @see org.xtext.example.rml.iRML.impl.IRMLPackageImpl#getLiteral()
   * @generated
   */
  int LITERAL = 14;

  /**
   * The feature id for the '<em><b>Language String</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LITERAL__LANGUAGE_STRING = 0;

  /**
   * The feature id for the '<em><b>Datatype String</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LITERAL__DATATYPE_STRING = 1;

  /**
   * The feature id for the '<em><b>Dword</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LITERAL__DWORD = 2;

  /**
   * The feature id for the '<em><b>Real</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LITERAL__REAL = 3;

  /**
   * The feature id for the '<em><b>Decimal</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LITERAL__DECIMAL = 4;

  /**
   * The feature id for the '<em><b>Bool</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LITERAL__BOOL = 5;

  /**
   * The number of structural features of the '<em>Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LITERAL_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link org.xtext.example.rml.iRML.impl.DatatypeStringImpl <em>Datatype String</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.rml.iRML.impl.DatatypeStringImpl
   * @see org.xtext.example.rml.iRML.impl.IRMLPackageImpl#getDatatypeString()
   * @generated
   */
  int DATATYPE_STRING = 15;

  /**
   * The feature id for the '<em><b>Qutoed String</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATATYPE_STRING__QUTOED_STRING = 0;

  /**
   * The feature id for the '<em><b>Resource</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATATYPE_STRING__RESOURCE = 1;

  /**
   * The number of structural features of the '<em>Datatype String</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATATYPE_STRING_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.rml.iRML.impl.BlankImpl <em>Blank</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.rml.iRML.impl.BlankImpl
   * @see org.xtext.example.rml.iRML.impl.IRMLPackageImpl#getBlank()
   * @generated
   */
  int BLANK = 16;

  /**
   * The feature id for the '<em><b>Node ID</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BLANK__NODE_ID = 0;

  /**
   * The feature id for the '<em><b>Is Square</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BLANK__IS_SQUARE = 1;

  /**
   * The feature id for the '<em><b>Predicate Object List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BLANK__PREDICATE_OBJECT_LIST = 2;

  /**
   * The feature id for the '<em><b>Collection</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BLANK__COLLECTION = 3;

  /**
   * The number of structural features of the '<em>Blank</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BLANK_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.rml.iRML.impl.ItemListImpl <em>Item List</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.rml.iRML.impl.ItemListImpl
   * @see org.xtext.example.rml.iRML.impl.IRMLPackageImpl#getItemList()
   * @generated
   */
  int ITEM_LIST = 17;

  /**
   * The feature id for the '<em><b>Objects</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ITEM_LIST__OBJECTS = 0;

  /**
   * The number of structural features of the '<em>Item List</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ITEM_LIST_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.rml.iRML.impl.CollectionImpl <em>Collection</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.rml.iRML.impl.CollectionImpl
   * @see org.xtext.example.rml.iRML.impl.IRMLPackageImpl#getCollection()
   * @generated
   */
  int COLLECTION = 18;

  /**
   * The feature id for the '<em><b>Item List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLLECTION__ITEM_LIST = 0;

  /**
   * The number of structural features of the '<em>Collection</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLLECTION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.rml.iRML.impl.NodeIDImpl <em>Node ID</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.rml.iRML.impl.NodeIDImpl
   * @see org.xtext.example.rml.iRML.impl.IRMLPackageImpl#getNodeID()
   * @generated
   */
  int NODE_ID = 19;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE_ID__NAME = 0;

  /**
   * The number of structural features of the '<em>Node ID</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE_ID_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.rml.iRML.impl.QnameImpl <em>Qname</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.rml.iRML.impl.QnameImpl
   * @see org.xtext.example.rml.iRML.impl.IRMLPackageImpl#getQname()
   * @generated
   */
  int QNAME = 20;

  /**
   * The feature id for the '<em><b>Prefix Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QNAME__PREFIX_NAME = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QNAME__NAME = 1;

  /**
   * The number of structural features of the '<em>Qname</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QNAME_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link org.xtext.example.rml.iRML.Mapping <em>Mapping</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Mapping</em>'.
   * @see org.xtext.example.rml.iRML.Mapping
   * @generated
   */
  EClass getMapping();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.rml.iRML.Mapping#getStatements <em>Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statements</em>'.
   * @see org.xtext.example.rml.iRML.Mapping#getStatements()
   * @see #getMapping()
   * @generated
   */
  EReference getMapping_Statements();

  /**
   * Returns the meta object for class '{@link org.xtext.example.rml.iRML.Statement <em>Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Statement</em>'.
   * @see org.xtext.example.rml.iRML.Statement
   * @generated
   */
  EClass getStatement();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.rml.iRML.Statement#getDirective <em>Directive</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Directive</em>'.
   * @see org.xtext.example.rml.iRML.Statement#getDirective()
   * @see #getStatement()
   * @generated
   */
  EReference getStatement_Directive();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.rml.iRML.Statement#getTriple <em>Triple</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Triple</em>'.
   * @see org.xtext.example.rml.iRML.Statement#getTriple()
   * @see #getStatement()
   * @generated
   */
  EReference getStatement_Triple();

  /**
   * Returns the meta object for class '{@link org.xtext.example.rml.iRML.Directive <em>Directive</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Directive</em>'.
   * @see org.xtext.example.rml.iRML.Directive
   * @generated
   */
  EClass getDirective();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.rml.iRML.Directive#getPrefix <em>Prefix</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Prefix</em>'.
   * @see org.xtext.example.rml.iRML.Directive#getPrefix()
   * @see #getDirective()
   * @generated
   */
  EReference getDirective_Prefix();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.rml.iRML.Directive#getBase <em>Base</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Base</em>'.
   * @see org.xtext.example.rml.iRML.Directive#getBase()
   * @see #getDirective()
   * @generated
   */
  EReference getDirective_Base();

  /**
   * Returns the meta object for class '{@link org.xtext.example.rml.iRML.PrefixID <em>Prefix ID</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Prefix ID</em>'.
   * @see org.xtext.example.rml.iRML.PrefixID
   * @generated
   */
  EClass getPrefixID();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.rml.iRML.PrefixID#getPrefixName <em>Prefix Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Prefix Name</em>'.
   * @see org.xtext.example.rml.iRML.PrefixID#getPrefixName()
   * @see #getPrefixID()
   * @generated
   */
  EAttribute getPrefixID_PrefixName();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.rml.iRML.PrefixID#getUriRef <em>Uri Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Uri Ref</em>'.
   * @see org.xtext.example.rml.iRML.PrefixID#getUriRef()
   * @see #getPrefixID()
   * @generated
   */
  EAttribute getPrefixID_UriRef();

  /**
   * Returns the meta object for class '{@link org.xtext.example.rml.iRML.Base <em>Base</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Base</em>'.
   * @see org.xtext.example.rml.iRML.Base
   * @generated
   */
  EClass getBase();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.rml.iRML.Base#getUriRef <em>Uri Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Uri Ref</em>'.
   * @see org.xtext.example.rml.iRML.Base#getUriRef()
   * @see #getBase()
   * @generated
   */
  EAttribute getBase_UriRef();

  /**
   * Returns the meta object for class '{@link org.xtext.example.rml.iRML.Triples <em>Triples</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Triples</em>'.
   * @see org.xtext.example.rml.iRML.Triples
   * @generated
   */
  EClass getTriples();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.rml.iRML.Triples#getSubject <em>Subject</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Subject</em>'.
   * @see org.xtext.example.rml.iRML.Triples#getSubject()
   * @see #getTriples()
   * @generated
   */
  EReference getTriples_Subject();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.rml.iRML.Triples#getPredicateObjectList <em>Predicate Object List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Predicate Object List</em>'.
   * @see org.xtext.example.rml.iRML.Triples#getPredicateObjectList()
   * @see #getTriples()
   * @generated
   */
  EReference getTriples_PredicateObjectList();

  /**
   * Returns the meta object for class '{@link org.xtext.example.rml.iRML.PredicateObject <em>Predicate Object</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Predicate Object</em>'.
   * @see org.xtext.example.rml.iRML.PredicateObject
   * @generated
   */
  EClass getPredicateObject();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.rml.iRML.PredicateObject#getVerb <em>Verb</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Verb</em>'.
   * @see org.xtext.example.rml.iRML.PredicateObject#getVerb()
   * @see #getPredicateObject()
   * @generated
   */
  EReference getPredicateObject_Verb();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.rml.iRML.PredicateObject#getObjectList <em>Object List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Object List</em>'.
   * @see org.xtext.example.rml.iRML.PredicateObject#getObjectList()
   * @see #getPredicateObject()
   * @generated
   */
  EReference getPredicateObject_ObjectList();

  /**
   * Returns the meta object for class '{@link org.xtext.example.rml.iRML.PredicateObjectList <em>Predicate Object List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Predicate Object List</em>'.
   * @see org.xtext.example.rml.iRML.PredicateObjectList
   * @generated
   */
  EClass getPredicateObjectList();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.rml.iRML.PredicateObjectList#getPredicateObjects <em>Predicate Objects</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Predicate Objects</em>'.
   * @see org.xtext.example.rml.iRML.PredicateObjectList#getPredicateObjects()
   * @see #getPredicateObjectList()
   * @generated
   */
  EReference getPredicateObjectList_PredicateObjects();

  /**
   * Returns the meta object for class '{@link org.xtext.example.rml.iRML.ObjectList <em>Object List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Object List</em>'.
   * @see org.xtext.example.rml.iRML.ObjectList
   * @generated
   */
  EClass getObjectList();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.rml.iRML.ObjectList#getObjects <em>Objects</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Objects</em>'.
   * @see org.xtext.example.rml.iRML.ObjectList#getObjects()
   * @see #getObjectList()
   * @generated
   */
  EReference getObjectList_Objects();

  /**
   * Returns the meta object for class '{@link org.xtext.example.rml.iRML.Verb <em>Verb</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Verb</em>'.
   * @see org.xtext.example.rml.iRML.Verb
   * @generated
   */
  EClass getVerb();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.rml.iRML.Verb#getPredicate <em>Predicate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Predicate</em>'.
   * @see org.xtext.example.rml.iRML.Verb#getPredicate()
   * @see #getVerb()
   * @generated
   */
  EReference getVerb_Predicate();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.rml.iRML.Verb#isIsA <em>Is A</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Is A</em>'.
   * @see org.xtext.example.rml.iRML.Verb#isIsA()
   * @see #getVerb()
   * @generated
   */
  EAttribute getVerb_IsA();

  /**
   * Returns the meta object for class '{@link org.xtext.example.rml.iRML.Subject <em>Subject</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Subject</em>'.
   * @see org.xtext.example.rml.iRML.Subject
   * @generated
   */
  EClass getSubject();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.rml.iRML.Subject#getResource <em>Resource</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Resource</em>'.
   * @see org.xtext.example.rml.iRML.Subject#getResource()
   * @see #getSubject()
   * @generated
   */
  EReference getSubject_Resource();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.rml.iRML.Subject#getBlank <em>Blank</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Blank</em>'.
   * @see org.xtext.example.rml.iRML.Subject#getBlank()
   * @see #getSubject()
   * @generated
   */
  EReference getSubject_Blank();

  /**
   * Returns the meta object for class '{@link org.xtext.example.rml.iRML.iResource <em>iResource</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>iResource</em>'.
   * @see org.xtext.example.rml.iRML.iResource
   * @generated
   */
  EClass getiResource();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.rml.iRML.iResource#getUriRef <em>Uri Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Uri Ref</em>'.
   * @see org.xtext.example.rml.iRML.iResource#getUriRef()
   * @see #getiResource()
   * @generated
   */
  EAttribute getiResource_UriRef();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.rml.iRML.iResource#getQname <em>Qname</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Qname</em>'.
   * @see org.xtext.example.rml.iRML.iResource#getQname()
   * @see #getiResource()
   * @generated
   */
  EReference getiResource_Qname();

  /**
   * Returns the meta object for class '{@link org.xtext.example.rml.iRML.Object <em>Object</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Object</em>'.
   * @see org.xtext.example.rml.iRML.Object
   * @generated
   */
  EClass getObject();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.rml.iRML.Object#getResource <em>Resource</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Resource</em>'.
   * @see org.xtext.example.rml.iRML.Object#getResource()
   * @see #getObject()
   * @generated
   */
  EReference getObject_Resource();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.rml.iRML.Object#getBlank <em>Blank</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Blank</em>'.
   * @see org.xtext.example.rml.iRML.Object#getBlank()
   * @see #getObject()
   * @generated
   */
  EReference getObject_Blank();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.rml.iRML.Object#getLiteral <em>Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Literal</em>'.
   * @see org.xtext.example.rml.iRML.Object#getLiteral()
   * @see #getObject()
   * @generated
   */
  EReference getObject_Literal();

  /**
   * Returns the meta object for class '{@link org.xtext.example.rml.iRML.LanguageString <em>Language String</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Language String</em>'.
   * @see org.xtext.example.rml.iRML.LanguageString
   * @generated
   */
  EClass getLanguageString();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.rml.iRML.LanguageString#getQutoedString <em>Qutoed String</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Qutoed String</em>'.
   * @see org.xtext.example.rml.iRML.LanguageString#getQutoedString()
   * @see #getLanguageString()
   * @generated
   */
  EAttribute getLanguageString_QutoedString();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.rml.iRML.LanguageString#getLang <em>Lang</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Lang</em>'.
   * @see org.xtext.example.rml.iRML.LanguageString#getLang()
   * @see #getLanguageString()
   * @generated
   */
  EAttribute getLanguageString_Lang();

  /**
   * Returns the meta object for class '{@link org.xtext.example.rml.iRML.Literal <em>Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Literal</em>'.
   * @see org.xtext.example.rml.iRML.Literal
   * @generated
   */
  EClass getLiteral();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.rml.iRML.Literal#getLanguageString <em>Language String</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Language String</em>'.
   * @see org.xtext.example.rml.iRML.Literal#getLanguageString()
   * @see #getLiteral()
   * @generated
   */
  EReference getLiteral_LanguageString();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.rml.iRML.Literal#getDatatypeString <em>Datatype String</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Datatype String</em>'.
   * @see org.xtext.example.rml.iRML.Literal#getDatatypeString()
   * @see #getLiteral()
   * @generated
   */
  EReference getLiteral_DatatypeString();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.rml.iRML.Literal#getDword <em>Dword</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Dword</em>'.
   * @see org.xtext.example.rml.iRML.Literal#getDword()
   * @see #getLiteral()
   * @generated
   */
  EAttribute getLiteral_Dword();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.rml.iRML.Literal#getReal <em>Real</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Real</em>'.
   * @see org.xtext.example.rml.iRML.Literal#getReal()
   * @see #getLiteral()
   * @generated
   */
  EAttribute getLiteral_Real();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.rml.iRML.Literal#getDecimal <em>Decimal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Decimal</em>'.
   * @see org.xtext.example.rml.iRML.Literal#getDecimal()
   * @see #getLiteral()
   * @generated
   */
  EAttribute getLiteral_Decimal();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.rml.iRML.Literal#getBool <em>Bool</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Bool</em>'.
   * @see org.xtext.example.rml.iRML.Literal#getBool()
   * @see #getLiteral()
   * @generated
   */
  EAttribute getLiteral_Bool();

  /**
   * Returns the meta object for class '{@link org.xtext.example.rml.iRML.DatatypeString <em>Datatype String</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Datatype String</em>'.
   * @see org.xtext.example.rml.iRML.DatatypeString
   * @generated
   */
  EClass getDatatypeString();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.rml.iRML.DatatypeString#getQutoedString <em>Qutoed String</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Qutoed String</em>'.
   * @see org.xtext.example.rml.iRML.DatatypeString#getQutoedString()
   * @see #getDatatypeString()
   * @generated
   */
  EAttribute getDatatypeString_QutoedString();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.rml.iRML.DatatypeString#getResource <em>Resource</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Resource</em>'.
   * @see org.xtext.example.rml.iRML.DatatypeString#getResource()
   * @see #getDatatypeString()
   * @generated
   */
  EReference getDatatypeString_Resource();

  /**
   * Returns the meta object for class '{@link org.xtext.example.rml.iRML.Blank <em>Blank</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Blank</em>'.
   * @see org.xtext.example.rml.iRML.Blank
   * @generated
   */
  EClass getBlank();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.rml.iRML.Blank#getNodeID <em>Node ID</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Node ID</em>'.
   * @see org.xtext.example.rml.iRML.Blank#getNodeID()
   * @see #getBlank()
   * @generated
   */
  EReference getBlank_NodeID();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.rml.iRML.Blank#isIsSquare <em>Is Square</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Is Square</em>'.
   * @see org.xtext.example.rml.iRML.Blank#isIsSquare()
   * @see #getBlank()
   * @generated
   */
  EAttribute getBlank_IsSquare();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.rml.iRML.Blank#getPredicateObjectList <em>Predicate Object List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Predicate Object List</em>'.
   * @see org.xtext.example.rml.iRML.Blank#getPredicateObjectList()
   * @see #getBlank()
   * @generated
   */
  EReference getBlank_PredicateObjectList();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.rml.iRML.Blank#getCollection <em>Collection</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Collection</em>'.
   * @see org.xtext.example.rml.iRML.Blank#getCollection()
   * @see #getBlank()
   * @generated
   */
  EReference getBlank_Collection();

  /**
   * Returns the meta object for class '{@link org.xtext.example.rml.iRML.ItemList <em>Item List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Item List</em>'.
   * @see org.xtext.example.rml.iRML.ItemList
   * @generated
   */
  EClass getItemList();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.rml.iRML.ItemList#getObjects <em>Objects</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Objects</em>'.
   * @see org.xtext.example.rml.iRML.ItemList#getObjects()
   * @see #getItemList()
   * @generated
   */
  EReference getItemList_Objects();

  /**
   * Returns the meta object for class '{@link org.xtext.example.rml.iRML.Collection <em>Collection</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Collection</em>'.
   * @see org.xtext.example.rml.iRML.Collection
   * @generated
   */
  EClass getCollection();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.rml.iRML.Collection#getItemList <em>Item List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Item List</em>'.
   * @see org.xtext.example.rml.iRML.Collection#getItemList()
   * @see #getCollection()
   * @generated
   */
  EReference getCollection_ItemList();

  /**
   * Returns the meta object for class '{@link org.xtext.example.rml.iRML.NodeID <em>Node ID</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Node ID</em>'.
   * @see org.xtext.example.rml.iRML.NodeID
   * @generated
   */
  EClass getNodeID();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.rml.iRML.NodeID#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.rml.iRML.NodeID#getName()
   * @see #getNodeID()
   * @generated
   */
  EAttribute getNodeID_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.rml.iRML.Qname <em>Qname</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Qname</em>'.
   * @see org.xtext.example.rml.iRML.Qname
   * @generated
   */
  EClass getQname();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.rml.iRML.Qname#getPrefixName <em>Prefix Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Prefix Name</em>'.
   * @see org.xtext.example.rml.iRML.Qname#getPrefixName()
   * @see #getQname()
   * @generated
   */
  EAttribute getQname_PrefixName();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.rml.iRML.Qname#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.rml.iRML.Qname#getName()
   * @see #getQname()
   * @generated
   */
  EAttribute getQname_Name();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  IRMLFactory getIRMLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.rml.iRML.impl.MappingImpl <em>Mapping</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.rml.iRML.impl.MappingImpl
     * @see org.xtext.example.rml.iRML.impl.IRMLPackageImpl#getMapping()
     * @generated
     */
    EClass MAPPING = eINSTANCE.getMapping();

    /**
     * The meta object literal for the '<em><b>Statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MAPPING__STATEMENTS = eINSTANCE.getMapping_Statements();

    /**
     * The meta object literal for the '{@link org.xtext.example.rml.iRML.impl.StatementImpl <em>Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.rml.iRML.impl.StatementImpl
     * @see org.xtext.example.rml.iRML.impl.IRMLPackageImpl#getStatement()
     * @generated
     */
    EClass STATEMENT = eINSTANCE.getStatement();

    /**
     * The meta object literal for the '<em><b>Directive</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATEMENT__DIRECTIVE = eINSTANCE.getStatement_Directive();

    /**
     * The meta object literal for the '<em><b>Triple</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATEMENT__TRIPLE = eINSTANCE.getStatement_Triple();

    /**
     * The meta object literal for the '{@link org.xtext.example.rml.iRML.impl.DirectiveImpl <em>Directive</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.rml.iRML.impl.DirectiveImpl
     * @see org.xtext.example.rml.iRML.impl.IRMLPackageImpl#getDirective()
     * @generated
     */
    EClass DIRECTIVE = eINSTANCE.getDirective();

    /**
     * The meta object literal for the '<em><b>Prefix</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DIRECTIVE__PREFIX = eINSTANCE.getDirective_Prefix();

    /**
     * The meta object literal for the '<em><b>Base</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DIRECTIVE__BASE = eINSTANCE.getDirective_Base();

    /**
     * The meta object literal for the '{@link org.xtext.example.rml.iRML.impl.PrefixIDImpl <em>Prefix ID</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.rml.iRML.impl.PrefixIDImpl
     * @see org.xtext.example.rml.iRML.impl.IRMLPackageImpl#getPrefixID()
     * @generated
     */
    EClass PREFIX_ID = eINSTANCE.getPrefixID();

    /**
     * The meta object literal for the '<em><b>Prefix Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PREFIX_ID__PREFIX_NAME = eINSTANCE.getPrefixID_PrefixName();

    /**
     * The meta object literal for the '<em><b>Uri Ref</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PREFIX_ID__URI_REF = eINSTANCE.getPrefixID_UriRef();

    /**
     * The meta object literal for the '{@link org.xtext.example.rml.iRML.impl.BaseImpl <em>Base</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.rml.iRML.impl.BaseImpl
     * @see org.xtext.example.rml.iRML.impl.IRMLPackageImpl#getBase()
     * @generated
     */
    EClass BASE = eINSTANCE.getBase();

    /**
     * The meta object literal for the '<em><b>Uri Ref</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BASE__URI_REF = eINSTANCE.getBase_UriRef();

    /**
     * The meta object literal for the '{@link org.xtext.example.rml.iRML.impl.TriplesImpl <em>Triples</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.rml.iRML.impl.TriplesImpl
     * @see org.xtext.example.rml.iRML.impl.IRMLPackageImpl#getTriples()
     * @generated
     */
    EClass TRIPLES = eINSTANCE.getTriples();

    /**
     * The meta object literal for the '<em><b>Subject</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRIPLES__SUBJECT = eINSTANCE.getTriples_Subject();

    /**
     * The meta object literal for the '<em><b>Predicate Object List</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRIPLES__PREDICATE_OBJECT_LIST = eINSTANCE.getTriples_PredicateObjectList();

    /**
     * The meta object literal for the '{@link org.xtext.example.rml.iRML.impl.PredicateObjectImpl <em>Predicate Object</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.rml.iRML.impl.PredicateObjectImpl
     * @see org.xtext.example.rml.iRML.impl.IRMLPackageImpl#getPredicateObject()
     * @generated
     */
    EClass PREDICATE_OBJECT = eINSTANCE.getPredicateObject();

    /**
     * The meta object literal for the '<em><b>Verb</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PREDICATE_OBJECT__VERB = eINSTANCE.getPredicateObject_Verb();

    /**
     * The meta object literal for the '<em><b>Object List</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PREDICATE_OBJECT__OBJECT_LIST = eINSTANCE.getPredicateObject_ObjectList();

    /**
     * The meta object literal for the '{@link org.xtext.example.rml.iRML.impl.PredicateObjectListImpl <em>Predicate Object List</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.rml.iRML.impl.PredicateObjectListImpl
     * @see org.xtext.example.rml.iRML.impl.IRMLPackageImpl#getPredicateObjectList()
     * @generated
     */
    EClass PREDICATE_OBJECT_LIST = eINSTANCE.getPredicateObjectList();

    /**
     * The meta object literal for the '<em><b>Predicate Objects</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PREDICATE_OBJECT_LIST__PREDICATE_OBJECTS = eINSTANCE.getPredicateObjectList_PredicateObjects();

    /**
     * The meta object literal for the '{@link org.xtext.example.rml.iRML.impl.ObjectListImpl <em>Object List</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.rml.iRML.impl.ObjectListImpl
     * @see org.xtext.example.rml.iRML.impl.IRMLPackageImpl#getObjectList()
     * @generated
     */
    EClass OBJECT_LIST = eINSTANCE.getObjectList();

    /**
     * The meta object literal for the '<em><b>Objects</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OBJECT_LIST__OBJECTS = eINSTANCE.getObjectList_Objects();

    /**
     * The meta object literal for the '{@link org.xtext.example.rml.iRML.impl.VerbImpl <em>Verb</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.rml.iRML.impl.VerbImpl
     * @see org.xtext.example.rml.iRML.impl.IRMLPackageImpl#getVerb()
     * @generated
     */
    EClass VERB = eINSTANCE.getVerb();

    /**
     * The meta object literal for the '<em><b>Predicate</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VERB__PREDICATE = eINSTANCE.getVerb_Predicate();

    /**
     * The meta object literal for the '<em><b>Is A</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VERB__IS_A = eINSTANCE.getVerb_IsA();

    /**
     * The meta object literal for the '{@link org.xtext.example.rml.iRML.impl.SubjectImpl <em>Subject</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.rml.iRML.impl.SubjectImpl
     * @see org.xtext.example.rml.iRML.impl.IRMLPackageImpl#getSubject()
     * @generated
     */
    EClass SUBJECT = eINSTANCE.getSubject();

    /**
     * The meta object literal for the '<em><b>Resource</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SUBJECT__RESOURCE = eINSTANCE.getSubject_Resource();

    /**
     * The meta object literal for the '<em><b>Blank</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SUBJECT__BLANK = eINSTANCE.getSubject_Blank();

    /**
     * The meta object literal for the '{@link org.xtext.example.rml.iRML.impl.iResourceImpl <em>iResource</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.rml.iRML.impl.iResourceImpl
     * @see org.xtext.example.rml.iRML.impl.IRMLPackageImpl#getiResource()
     * @generated
     */
    EClass IRESOURCE = eINSTANCE.getiResource();

    /**
     * The meta object literal for the '<em><b>Uri Ref</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IRESOURCE__URI_REF = eINSTANCE.getiResource_UriRef();

    /**
     * The meta object literal for the '<em><b>Qname</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IRESOURCE__QNAME = eINSTANCE.getiResource_Qname();

    /**
     * The meta object literal for the '{@link org.xtext.example.rml.iRML.impl.ObjectImpl <em>Object</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.rml.iRML.impl.ObjectImpl
     * @see org.xtext.example.rml.iRML.impl.IRMLPackageImpl#getObject()
     * @generated
     */
    EClass OBJECT = eINSTANCE.getObject();

    /**
     * The meta object literal for the '<em><b>Resource</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OBJECT__RESOURCE = eINSTANCE.getObject_Resource();

    /**
     * The meta object literal for the '<em><b>Blank</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OBJECT__BLANK = eINSTANCE.getObject_Blank();

    /**
     * The meta object literal for the '<em><b>Literal</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OBJECT__LITERAL = eINSTANCE.getObject_Literal();

    /**
     * The meta object literal for the '{@link org.xtext.example.rml.iRML.impl.LanguageStringImpl <em>Language String</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.rml.iRML.impl.LanguageStringImpl
     * @see org.xtext.example.rml.iRML.impl.IRMLPackageImpl#getLanguageString()
     * @generated
     */
    EClass LANGUAGE_STRING = eINSTANCE.getLanguageString();

    /**
     * The meta object literal for the '<em><b>Qutoed String</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LANGUAGE_STRING__QUTOED_STRING = eINSTANCE.getLanguageString_QutoedString();

    /**
     * The meta object literal for the '<em><b>Lang</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LANGUAGE_STRING__LANG = eINSTANCE.getLanguageString_Lang();

    /**
     * The meta object literal for the '{@link org.xtext.example.rml.iRML.impl.LiteralImpl <em>Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.rml.iRML.impl.LiteralImpl
     * @see org.xtext.example.rml.iRML.impl.IRMLPackageImpl#getLiteral()
     * @generated
     */
    EClass LITERAL = eINSTANCE.getLiteral();

    /**
     * The meta object literal for the '<em><b>Language String</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LITERAL__LANGUAGE_STRING = eINSTANCE.getLiteral_LanguageString();

    /**
     * The meta object literal for the '<em><b>Datatype String</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LITERAL__DATATYPE_STRING = eINSTANCE.getLiteral_DatatypeString();

    /**
     * The meta object literal for the '<em><b>Dword</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LITERAL__DWORD = eINSTANCE.getLiteral_Dword();

    /**
     * The meta object literal for the '<em><b>Real</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LITERAL__REAL = eINSTANCE.getLiteral_Real();

    /**
     * The meta object literal for the '<em><b>Decimal</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LITERAL__DECIMAL = eINSTANCE.getLiteral_Decimal();

    /**
     * The meta object literal for the '<em><b>Bool</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LITERAL__BOOL = eINSTANCE.getLiteral_Bool();

    /**
     * The meta object literal for the '{@link org.xtext.example.rml.iRML.impl.DatatypeStringImpl <em>Datatype String</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.rml.iRML.impl.DatatypeStringImpl
     * @see org.xtext.example.rml.iRML.impl.IRMLPackageImpl#getDatatypeString()
     * @generated
     */
    EClass DATATYPE_STRING = eINSTANCE.getDatatypeString();

    /**
     * The meta object literal for the '<em><b>Qutoed String</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DATATYPE_STRING__QUTOED_STRING = eINSTANCE.getDatatypeString_QutoedString();

    /**
     * The meta object literal for the '<em><b>Resource</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DATATYPE_STRING__RESOURCE = eINSTANCE.getDatatypeString_Resource();

    /**
     * The meta object literal for the '{@link org.xtext.example.rml.iRML.impl.BlankImpl <em>Blank</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.rml.iRML.impl.BlankImpl
     * @see org.xtext.example.rml.iRML.impl.IRMLPackageImpl#getBlank()
     * @generated
     */
    EClass BLANK = eINSTANCE.getBlank();

    /**
     * The meta object literal for the '<em><b>Node ID</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BLANK__NODE_ID = eINSTANCE.getBlank_NodeID();

    /**
     * The meta object literal for the '<em><b>Is Square</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BLANK__IS_SQUARE = eINSTANCE.getBlank_IsSquare();

    /**
     * The meta object literal for the '<em><b>Predicate Object List</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BLANK__PREDICATE_OBJECT_LIST = eINSTANCE.getBlank_PredicateObjectList();

    /**
     * The meta object literal for the '<em><b>Collection</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BLANK__COLLECTION = eINSTANCE.getBlank_Collection();

    /**
     * The meta object literal for the '{@link org.xtext.example.rml.iRML.impl.ItemListImpl <em>Item List</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.rml.iRML.impl.ItemListImpl
     * @see org.xtext.example.rml.iRML.impl.IRMLPackageImpl#getItemList()
     * @generated
     */
    EClass ITEM_LIST = eINSTANCE.getItemList();

    /**
     * The meta object literal for the '<em><b>Objects</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ITEM_LIST__OBJECTS = eINSTANCE.getItemList_Objects();

    /**
     * The meta object literal for the '{@link org.xtext.example.rml.iRML.impl.CollectionImpl <em>Collection</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.rml.iRML.impl.CollectionImpl
     * @see org.xtext.example.rml.iRML.impl.IRMLPackageImpl#getCollection()
     * @generated
     */
    EClass COLLECTION = eINSTANCE.getCollection();

    /**
     * The meta object literal for the '<em><b>Item List</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COLLECTION__ITEM_LIST = eINSTANCE.getCollection_ItemList();

    /**
     * The meta object literal for the '{@link org.xtext.example.rml.iRML.impl.NodeIDImpl <em>Node ID</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.rml.iRML.impl.NodeIDImpl
     * @see org.xtext.example.rml.iRML.impl.IRMLPackageImpl#getNodeID()
     * @generated
     */
    EClass NODE_ID = eINSTANCE.getNodeID();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NODE_ID__NAME = eINSTANCE.getNodeID_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.rml.iRML.impl.QnameImpl <em>Qname</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.rml.iRML.impl.QnameImpl
     * @see org.xtext.example.rml.iRML.impl.IRMLPackageImpl#getQname()
     * @generated
     */
    EClass QNAME = eINSTANCE.getQname();

    /**
     * The meta object literal for the '<em><b>Prefix Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute QNAME__PREFIX_NAME = eINSTANCE.getQname_PrefixName();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute QNAME__NAME = eINSTANCE.getQname_Name();

  }

} //IRMLPackage
