/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.rml.iRML;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Language String</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.rml.iRML.LanguageString#getQutoedString <em>Qutoed String</em>}</li>
 *   <li>{@link org.xtext.example.rml.iRML.LanguageString#getLang <em>Lang</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.rml.iRML.IRMLPackage#getLanguageString()
 * @model
 * @generated
 */
public interface LanguageString extends EObject
{
  /**
   * Returns the value of the '<em><b>Qutoed String</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Qutoed String</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Qutoed String</em>' attribute.
   * @see #setQutoedString(String)
   * @see org.xtext.example.rml.iRML.IRMLPackage#getLanguageString_QutoedString()
   * @model
   * @generated
   */
  String getQutoedString();

  /**
   * Sets the value of the '{@link org.xtext.example.rml.iRML.LanguageString#getQutoedString <em>Qutoed String</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Qutoed String</em>' attribute.
   * @see #getQutoedString()
   * @generated
   */
  void setQutoedString(String value);

  /**
   * Returns the value of the '<em><b>Lang</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Lang</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lang</em>' attribute.
   * @see #setLang(String)
   * @see org.xtext.example.rml.iRML.IRMLPackage#getLanguageString_Lang()
   * @model
   * @generated
   */
  String getLang();

  /**
   * Sets the value of the '{@link org.xtext.example.rml.iRML.LanguageString#getLang <em>Lang</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Lang</em>' attribute.
   * @see #getLang()
   * @generated
   */
  void setLang(String value);

} // LanguageString
