/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.rml.iRML;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Literal</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.rml.iRML.Literal#getLanguageString <em>Language String</em>}</li>
 *   <li>{@link org.xtext.example.rml.iRML.Literal#getDatatypeString <em>Datatype String</em>}</li>
 *   <li>{@link org.xtext.example.rml.iRML.Literal#getDword <em>Dword</em>}</li>
 *   <li>{@link org.xtext.example.rml.iRML.Literal#getReal <em>Real</em>}</li>
 *   <li>{@link org.xtext.example.rml.iRML.Literal#getDecimal <em>Decimal</em>}</li>
 *   <li>{@link org.xtext.example.rml.iRML.Literal#getBool <em>Bool</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.rml.iRML.IRMLPackage#getLiteral()
 * @model
 * @generated
 */
public interface Literal extends EObject
{
  /**
   * Returns the value of the '<em><b>Language String</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Language String</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Language String</em>' containment reference.
   * @see #setLanguageString(LanguageString)
   * @see org.xtext.example.rml.iRML.IRMLPackage#getLiteral_LanguageString()
   * @model containment="true"
   * @generated
   */
  LanguageString getLanguageString();

  /**
   * Sets the value of the '{@link org.xtext.example.rml.iRML.Literal#getLanguageString <em>Language String</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Language String</em>' containment reference.
   * @see #getLanguageString()
   * @generated
   */
  void setLanguageString(LanguageString value);

  /**
   * Returns the value of the '<em><b>Datatype String</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Datatype String</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Datatype String</em>' containment reference.
   * @see #setDatatypeString(DatatypeString)
   * @see org.xtext.example.rml.iRML.IRMLPackage#getLiteral_DatatypeString()
   * @model containment="true"
   * @generated
   */
  DatatypeString getDatatypeString();

  /**
   * Sets the value of the '{@link org.xtext.example.rml.iRML.Literal#getDatatypeString <em>Datatype String</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Datatype String</em>' containment reference.
   * @see #getDatatypeString()
   * @generated
   */
  void setDatatypeString(DatatypeString value);

  /**
   * Returns the value of the '<em><b>Dword</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Dword</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dword</em>' attribute.
   * @see #setDword(int)
   * @see org.xtext.example.rml.iRML.IRMLPackage#getLiteral_Dword()
   * @model
   * @generated
   */
  int getDword();

  /**
   * Sets the value of the '{@link org.xtext.example.rml.iRML.Literal#getDword <em>Dword</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dword</em>' attribute.
   * @see #getDword()
   * @generated
   */
  void setDword(int value);

  /**
   * Returns the value of the '<em><b>Real</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Real</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Real</em>' attribute.
   * @see #setReal(String)
   * @see org.xtext.example.rml.iRML.IRMLPackage#getLiteral_Real()
   * @model
   * @generated
   */
  String getReal();

  /**
   * Sets the value of the '{@link org.xtext.example.rml.iRML.Literal#getReal <em>Real</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Real</em>' attribute.
   * @see #getReal()
   * @generated
   */
  void setReal(String value);

  /**
   * Returns the value of the '<em><b>Decimal</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Decimal</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Decimal</em>' attribute.
   * @see #setDecimal(String)
   * @see org.xtext.example.rml.iRML.IRMLPackage#getLiteral_Decimal()
   * @model
   * @generated
   */
  String getDecimal();

  /**
   * Sets the value of the '{@link org.xtext.example.rml.iRML.Literal#getDecimal <em>Decimal</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Decimal</em>' attribute.
   * @see #getDecimal()
   * @generated
   */
  void setDecimal(String value);

  /**
   * Returns the value of the '<em><b>Bool</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Bool</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bool</em>' attribute.
   * @see #setBool(String)
   * @see org.xtext.example.rml.iRML.IRMLPackage#getLiteral_Bool()
   * @model
   * @generated
   */
  String getBool();

  /**
   * Sets the value of the '{@link org.xtext.example.rml.iRML.Literal#getBool <em>Bool</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bool</em>' attribute.
   * @see #getBool()
   * @generated
   */
  void setBool(String value);

} // Literal
