/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.rml.iRML;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Object List</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.rml.iRML.ObjectList#getObjects <em>Objects</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.rml.iRML.IRMLPackage#getObjectList()
 * @model
 * @generated
 */
public interface ObjectList extends EObject
{
  /**
   * Returns the value of the '<em><b>Objects</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.rml.iRML.Object}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Objects</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Objects</em>' containment reference list.
   * @see org.xtext.example.rml.iRML.IRMLPackage#getObjectList_Objects()
   * @model containment="true"
   * @generated
   */
  EList<org.xtext.example.rml.iRML.Object> getObjects();

} // ObjectList
