/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.rml.iRML;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Object</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.rml.iRML.Object#getResource <em>Resource</em>}</li>
 *   <li>{@link org.xtext.example.rml.iRML.Object#getBlank <em>Blank</em>}</li>
 *   <li>{@link org.xtext.example.rml.iRML.Object#getLiteral <em>Literal</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.rml.iRML.IRMLPackage#getObject()
 * @model
 * @generated
 */
public interface Object extends EObject
{
  /**
   * Returns the value of the '<em><b>Resource</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Resource</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Resource</em>' containment reference.
   * @see #setResource(iResource)
   * @see org.xtext.example.rml.iRML.IRMLPackage#getObject_Resource()
   * @model containment="true"
   * @generated
   */
  iResource getResource();

  /**
   * Sets the value of the '{@link org.xtext.example.rml.iRML.Object#getResource <em>Resource</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Resource</em>' containment reference.
   * @see #getResource()
   * @generated
   */
  void setResource(iResource value);

  /**
   * Returns the value of the '<em><b>Blank</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Blank</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Blank</em>' containment reference.
   * @see #setBlank(Blank)
   * @see org.xtext.example.rml.iRML.IRMLPackage#getObject_Blank()
   * @model containment="true"
   * @generated
   */
  Blank getBlank();

  /**
   * Sets the value of the '{@link org.xtext.example.rml.iRML.Object#getBlank <em>Blank</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Blank</em>' containment reference.
   * @see #getBlank()
   * @generated
   */
  void setBlank(Blank value);

  /**
   * Returns the value of the '<em><b>Literal</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Literal</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Literal</em>' containment reference.
   * @see #setLiteral(Literal)
   * @see org.xtext.example.rml.iRML.IRMLPackage#getObject_Literal()
   * @model containment="true"
   * @generated
   */
  Literal getLiteral();

  /**
   * Sets the value of the '{@link org.xtext.example.rml.iRML.Object#getLiteral <em>Literal</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Literal</em>' containment reference.
   * @see #getLiteral()
   * @generated
   */
  void setLiteral(Literal value);

} // Object
