/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.rml.iRML;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Predicate Object</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.rml.iRML.PredicateObject#getVerb <em>Verb</em>}</li>
 *   <li>{@link org.xtext.example.rml.iRML.PredicateObject#getObjectList <em>Object List</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.rml.iRML.IRMLPackage#getPredicateObject()
 * @model
 * @generated
 */
public interface PredicateObject extends EObject
{
  /**
   * Returns the value of the '<em><b>Verb</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Verb</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Verb</em>' containment reference.
   * @see #setVerb(Verb)
   * @see org.xtext.example.rml.iRML.IRMLPackage#getPredicateObject_Verb()
   * @model containment="true"
   * @generated
   */
  Verb getVerb();

  /**
   * Sets the value of the '{@link org.xtext.example.rml.iRML.PredicateObject#getVerb <em>Verb</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Verb</em>' containment reference.
   * @see #getVerb()
   * @generated
   */
  void setVerb(Verb value);

  /**
   * Returns the value of the '<em><b>Object List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Object List</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Object List</em>' containment reference.
   * @see #setObjectList(ObjectList)
   * @see org.xtext.example.rml.iRML.IRMLPackage#getPredicateObject_ObjectList()
   * @model containment="true"
   * @generated
   */
  ObjectList getObjectList();

  /**
   * Sets the value of the '{@link org.xtext.example.rml.iRML.PredicateObject#getObjectList <em>Object List</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Object List</em>' containment reference.
   * @see #getObjectList()
   * @generated
   */
  void setObjectList(ObjectList value);

} // PredicateObject
