/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.rml.iRML;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Prefix ID</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.rml.iRML.PrefixID#getPrefixName <em>Prefix Name</em>}</li>
 *   <li>{@link org.xtext.example.rml.iRML.PrefixID#getUriRef <em>Uri Ref</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.rml.iRML.IRMLPackage#getPrefixID()
 * @model
 * @generated
 */
public interface PrefixID extends EObject
{
  /**
   * Returns the value of the '<em><b>Prefix Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Prefix Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Prefix Name</em>' attribute.
   * @see #setPrefixName(String)
   * @see org.xtext.example.rml.iRML.IRMLPackage#getPrefixID_PrefixName()
   * @model
   * @generated
   */
  String getPrefixName();

  /**
   * Sets the value of the '{@link org.xtext.example.rml.iRML.PrefixID#getPrefixName <em>Prefix Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Prefix Name</em>' attribute.
   * @see #getPrefixName()
   * @generated
   */
  void setPrefixName(String value);

  /**
   * Returns the value of the '<em><b>Uri Ref</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Uri Ref</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Uri Ref</em>' attribute.
   * @see #setUriRef(String)
   * @see org.xtext.example.rml.iRML.IRMLPackage#getPrefixID_UriRef()
   * @model
   * @generated
   */
  String getUriRef();

  /**
   * Sets the value of the '{@link org.xtext.example.rml.iRML.PrefixID#getUriRef <em>Uri Ref</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Uri Ref</em>' attribute.
   * @see #getUriRef()
   * @generated
   */
  void setUriRef(String value);

} // PrefixID
