/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.rml.iRML;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.rml.iRML.Statement#getDirective <em>Directive</em>}</li>
 *   <li>{@link org.xtext.example.rml.iRML.Statement#getTriple <em>Triple</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.rml.iRML.IRMLPackage#getStatement()
 * @model
 * @generated
 */
public interface Statement extends EObject
{
  /**
   * Returns the value of the '<em><b>Directive</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Directive</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Directive</em>' containment reference.
   * @see #setDirective(Directive)
   * @see org.xtext.example.rml.iRML.IRMLPackage#getStatement_Directive()
   * @model containment="true"
   * @generated
   */
  Directive getDirective();

  /**
   * Sets the value of the '{@link org.xtext.example.rml.iRML.Statement#getDirective <em>Directive</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Directive</em>' containment reference.
   * @see #getDirective()
   * @generated
   */
  void setDirective(Directive value);

  /**
   * Returns the value of the '<em><b>Triple</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Triple</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Triple</em>' containment reference.
   * @see #setTriple(Triples)
   * @see org.xtext.example.rml.iRML.IRMLPackage#getStatement_Triple()
   * @model containment="true"
   * @generated
   */
  Triples getTriple();

  /**
   * Sets the value of the '{@link org.xtext.example.rml.iRML.Statement#getTriple <em>Triple</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Triple</em>' containment reference.
   * @see #getTriple()
   * @generated
   */
  void setTriple(Triples value);

} // Statement
