/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.rml.iRML;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Triples</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.rml.iRML.Triples#getSubject <em>Subject</em>}</li>
 *   <li>{@link org.xtext.example.rml.iRML.Triples#getPredicateObjectList <em>Predicate Object List</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.rml.iRML.IRMLPackage#getTriples()
 * @model
 * @generated
 */
public interface Triples extends EObject
{
  /**
   * Returns the value of the '<em><b>Subject</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Subject</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Subject</em>' containment reference.
   * @see #setSubject(Subject)
   * @see org.xtext.example.rml.iRML.IRMLPackage#getTriples_Subject()
   * @model containment="true"
   * @generated
   */
  Subject getSubject();

  /**
   * Sets the value of the '{@link org.xtext.example.rml.iRML.Triples#getSubject <em>Subject</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Subject</em>' containment reference.
   * @see #getSubject()
   * @generated
   */
  void setSubject(Subject value);

  /**
   * Returns the value of the '<em><b>Predicate Object List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Predicate Object List</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Predicate Object List</em>' containment reference.
   * @see #setPredicateObjectList(PredicateObjectList)
   * @see org.xtext.example.rml.iRML.IRMLPackage#getTriples_PredicateObjectList()
   * @model containment="true"
   * @generated
   */
  PredicateObjectList getPredicateObjectList();

  /**
   * Sets the value of the '{@link org.xtext.example.rml.iRML.Triples#getPredicateObjectList <em>Predicate Object List</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Predicate Object List</em>' containment reference.
   * @see #getPredicateObjectList()
   * @generated
   */
  void setPredicateObjectList(PredicateObjectList value);

} // Triples
