/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.rml.iRML.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.rml.iRML.DatatypeString;
import org.xtext.example.rml.iRML.IRMLPackage;
import org.xtext.example.rml.iRML.iResource;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Datatype String</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.rml.iRML.impl.DatatypeStringImpl#getQutoedString <em>Qutoed String</em>}</li>
 *   <li>{@link org.xtext.example.rml.iRML.impl.DatatypeStringImpl#getResource <em>Resource</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DatatypeStringImpl extends MinimalEObjectImpl.Container implements DatatypeString
{
  /**
   * The default value of the '{@link #getQutoedString() <em>Qutoed String</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getQutoedString()
   * @generated
   * @ordered
   */
  protected static final String QUTOED_STRING_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getQutoedString() <em>Qutoed String</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getQutoedString()
   * @generated
   * @ordered
   */
  protected String qutoedString = QUTOED_STRING_EDEFAULT;

  /**
   * The cached value of the '{@link #getResource() <em>Resource</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getResource()
   * @generated
   * @ordered
   */
  protected iResource resource;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DatatypeStringImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return IRMLPackage.Literals.DATATYPE_STRING;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getQutoedString()
  {
    return qutoedString;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setQutoedString(String newQutoedString)
  {
    String oldQutoedString = qutoedString;
    qutoedString = newQutoedString;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IRMLPackage.DATATYPE_STRING__QUTOED_STRING, oldQutoedString, qutoedString));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public iResource getResource()
  {
    return resource;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetResource(iResource newResource, NotificationChain msgs)
  {
    iResource oldResource = resource;
    resource = newResource;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, IRMLPackage.DATATYPE_STRING__RESOURCE, oldResource, newResource);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setResource(iResource newResource)
  {
    if (newResource != resource)
    {
      NotificationChain msgs = null;
      if (resource != null)
        msgs = ((InternalEObject)resource).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - IRMLPackage.DATATYPE_STRING__RESOURCE, null, msgs);
      if (newResource != null)
        msgs = ((InternalEObject)newResource).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - IRMLPackage.DATATYPE_STRING__RESOURCE, null, msgs);
      msgs = basicSetResource(newResource, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IRMLPackage.DATATYPE_STRING__RESOURCE, newResource, newResource));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case IRMLPackage.DATATYPE_STRING__RESOURCE:
        return basicSetResource(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case IRMLPackage.DATATYPE_STRING__QUTOED_STRING:
        return getQutoedString();
      case IRMLPackage.DATATYPE_STRING__RESOURCE:
        return getResource();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case IRMLPackage.DATATYPE_STRING__QUTOED_STRING:
        setQutoedString((String)newValue);
        return;
      case IRMLPackage.DATATYPE_STRING__RESOURCE:
        setResource((iResource)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case IRMLPackage.DATATYPE_STRING__QUTOED_STRING:
        setQutoedString(QUTOED_STRING_EDEFAULT);
        return;
      case IRMLPackage.DATATYPE_STRING__RESOURCE:
        setResource((iResource)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case IRMLPackage.DATATYPE_STRING__QUTOED_STRING:
        return QUTOED_STRING_EDEFAULT == null ? qutoedString != null : !QUTOED_STRING_EDEFAULT.equals(qutoedString);
      case IRMLPackage.DATATYPE_STRING__RESOURCE:
        return resource != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (qutoedString: ");
    result.append(qutoedString);
    result.append(')');
    return result.toString();
  }

} //DatatypeStringImpl
