/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.rml.iRML.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.rml.iRML.IRMLPackage;
import org.xtext.example.rml.iRML.Qname;
import org.xtext.example.rml.iRML.iResource;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>iResource</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.rml.iRML.impl.iResourceImpl#getUriRef <em>Uri Ref</em>}</li>
 *   <li>{@link org.xtext.example.rml.iRML.impl.iResourceImpl#getQname <em>Qname</em>}</li>
 * </ul>
 *
 * @generated
 */
public class iResourceImpl extends MinimalEObjectImpl.Container implements iResource
{
  /**
   * The default value of the '{@link #getUriRef() <em>Uri Ref</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUriRef()
   * @generated
   * @ordered
   */
  protected static final String URI_REF_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getUriRef() <em>Uri Ref</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUriRef()
   * @generated
   * @ordered
   */
  protected String uriRef = URI_REF_EDEFAULT;

  /**
   * The cached value of the '{@link #getQname() <em>Qname</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getQname()
   * @generated
   * @ordered
   */
  protected Qname qname;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected iResourceImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return IRMLPackage.Literals.IRESOURCE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getUriRef()
  {
    return uriRef;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setUriRef(String newUriRef)
  {
    String oldUriRef = uriRef;
    uriRef = newUriRef;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IRMLPackage.IRESOURCE__URI_REF, oldUriRef, uriRef));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Qname getQname()
  {
    return qname;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetQname(Qname newQname, NotificationChain msgs)
  {
    Qname oldQname = qname;
    qname = newQname;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, IRMLPackage.IRESOURCE__QNAME, oldQname, newQname);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setQname(Qname newQname)
  {
    if (newQname != qname)
    {
      NotificationChain msgs = null;
      if (qname != null)
        msgs = ((InternalEObject)qname).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - IRMLPackage.IRESOURCE__QNAME, null, msgs);
      if (newQname != null)
        msgs = ((InternalEObject)newQname).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - IRMLPackage.IRESOURCE__QNAME, null, msgs);
      msgs = basicSetQname(newQname, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IRMLPackage.IRESOURCE__QNAME, newQname, newQname));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case IRMLPackage.IRESOURCE__QNAME:
        return basicSetQname(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case IRMLPackage.IRESOURCE__URI_REF:
        return getUriRef();
      case IRMLPackage.IRESOURCE__QNAME:
        return getQname();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case IRMLPackage.IRESOURCE__URI_REF:
        setUriRef((String)newValue);
        return;
      case IRMLPackage.IRESOURCE__QNAME:
        setQname((Qname)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case IRMLPackage.IRESOURCE__URI_REF:
        setUriRef(URI_REF_EDEFAULT);
        return;
      case IRMLPackage.IRESOURCE__QNAME:
        setQname((Qname)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case IRMLPackage.IRESOURCE__URI_REF:
        return URI_REF_EDEFAULT == null ? uriRef != null : !URI_REF_EDEFAULT.equals(uriRef);
      case IRMLPackage.IRESOURCE__QNAME:
        return qname != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (uriRef: ");
    result.append(uriRef);
    result.append(')');
    return result.toString();
  }

} //iResourceImpl
