/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.rml.iRML.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import org.xtext.example.rml.iRML.Base;
import org.xtext.example.rml.iRML.Blank;
import org.xtext.example.rml.iRML.Collection;
import org.xtext.example.rml.iRML.DatatypeString;
import org.xtext.example.rml.iRML.Directive;
import org.xtext.example.rml.iRML.IRMLFactory;
import org.xtext.example.rml.iRML.IRMLPackage;
import org.xtext.example.rml.iRML.ItemList;
import org.xtext.example.rml.iRML.LanguageString;
import org.xtext.example.rml.iRML.Literal;
import org.xtext.example.rml.iRML.Mapping;
import org.xtext.example.rml.iRML.NodeID;
import org.xtext.example.rml.iRML.ObjectList;
import org.xtext.example.rml.iRML.PredicateObject;
import org.xtext.example.rml.iRML.PredicateObjectList;
import org.xtext.example.rml.iRML.PrefixID;
import org.xtext.example.rml.iRML.Qname;
import org.xtext.example.rml.iRML.Statement;
import org.xtext.example.rml.iRML.Subject;
import org.xtext.example.rml.iRML.Triples;
import org.xtext.example.rml.iRML.Verb;
import org.xtext.example.rml.iRML.iResource;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class IRMLFactoryImpl extends EFactoryImpl implements IRMLFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static IRMLFactory init()
  {
    try
    {
      IRMLFactory theIRMLFactory = (IRMLFactory)EPackage.Registry.INSTANCE.getEFactory(IRMLPackage.eNS_URI);
      if (theIRMLFactory != null)
      {
        return theIRMLFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new IRMLFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public IRMLFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case IRMLPackage.MAPPING: return createMapping();
      case IRMLPackage.STATEMENT: return createStatement();
      case IRMLPackage.DIRECTIVE: return createDirective();
      case IRMLPackage.PREFIX_ID: return createPrefixID();
      case IRMLPackage.BASE: return createBase();
      case IRMLPackage.TRIPLES: return createTriples();
      case IRMLPackage.PREDICATE_OBJECT: return createPredicateObject();
      case IRMLPackage.PREDICATE_OBJECT_LIST: return createPredicateObjectList();
      case IRMLPackage.OBJECT_LIST: return createObjectList();
      case IRMLPackage.VERB: return createVerb();
      case IRMLPackage.SUBJECT: return createSubject();
      case IRMLPackage.IRESOURCE: return createiResource();
      case IRMLPackage.OBJECT: return createObject();
      case IRMLPackage.LANGUAGE_STRING: return createLanguageString();
      case IRMLPackage.LITERAL: return createLiteral();
      case IRMLPackage.DATATYPE_STRING: return createDatatypeString();
      case IRMLPackage.BLANK: return createBlank();
      case IRMLPackage.ITEM_LIST: return createItemList();
      case IRMLPackage.COLLECTION: return createCollection();
      case IRMLPackage.NODE_ID: return createNodeID();
      case IRMLPackage.QNAME: return createQname();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Mapping createMapping()
  {
    MappingImpl mapping = new MappingImpl();
    return mapping;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Statement createStatement()
  {
    StatementImpl statement = new StatementImpl();
    return statement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Directive createDirective()
  {
    DirectiveImpl directive = new DirectiveImpl();
    return directive;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PrefixID createPrefixID()
  {
    PrefixIDImpl prefixID = new PrefixIDImpl();
    return prefixID;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Base createBase()
  {
    BaseImpl base = new BaseImpl();
    return base;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Triples createTriples()
  {
    TriplesImpl triples = new TriplesImpl();
    return triples;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PredicateObject createPredicateObject()
  {
    PredicateObjectImpl predicateObject = new PredicateObjectImpl();
    return predicateObject;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PredicateObjectList createPredicateObjectList()
  {
    PredicateObjectListImpl predicateObjectList = new PredicateObjectListImpl();
    return predicateObjectList;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ObjectList createObjectList()
  {
    ObjectListImpl objectList = new ObjectListImpl();
    return objectList;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Verb createVerb()
  {
    VerbImpl verb = new VerbImpl();
    return verb;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Subject createSubject()
  {
    SubjectImpl subject = new SubjectImpl();
    return subject;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public iResource createiResource()
  {
    iResourceImpl iResource = new iResourceImpl();
    return iResource;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public org.xtext.example.rml.iRML.Object createObject()
  {
    ObjectImpl object = new ObjectImpl();
    return object;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public LanguageString createLanguageString()
  {
    LanguageStringImpl languageString = new LanguageStringImpl();
    return languageString;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Literal createLiteral()
  {
    LiteralImpl literal = new LiteralImpl();
    return literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DatatypeString createDatatypeString()
  {
    DatatypeStringImpl datatypeString = new DatatypeStringImpl();
    return datatypeString;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Blank createBlank()
  {
    BlankImpl blank = new BlankImpl();
    return blank;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ItemList createItemList()
  {
    ItemListImpl itemList = new ItemListImpl();
    return itemList;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Collection createCollection()
  {
    CollectionImpl collection = new CollectionImpl();
    return collection;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NodeID createNodeID()
  {
    NodeIDImpl nodeID = new NodeIDImpl();
    return nodeID;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Qname createQname()
  {
    QnameImpl qname = new QnameImpl();
    return qname;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public IRMLPackage getIRMLPackage()
  {
    return (IRMLPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static IRMLPackage getPackage()
  {
    return IRMLPackage.eINSTANCE;
  }

} //IRMLFactoryImpl
