/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.rml.iRML.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.rml.iRML.IRMLPackage;
import org.xtext.example.rml.iRML.LanguageString;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Language String</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.rml.iRML.impl.LanguageStringImpl#getQutoedString <em>Qutoed String</em>}</li>
 *   <li>{@link org.xtext.example.rml.iRML.impl.LanguageStringImpl#getLang <em>Lang</em>}</li>
 * </ul>
 *
 * @generated
 */
public class LanguageStringImpl extends MinimalEObjectImpl.Container implements LanguageString
{
  /**
   * The default value of the '{@link #getQutoedString() <em>Qutoed String</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getQutoedString()
   * @generated
   * @ordered
   */
  protected static final String QUTOED_STRING_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getQutoedString() <em>Qutoed String</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getQutoedString()
   * @generated
   * @ordered
   */
  protected String qutoedString = QUTOED_STRING_EDEFAULT;

  /**
   * The default value of the '{@link #getLang() <em>Lang</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLang()
   * @generated
   * @ordered
   */
  protected static final String LANG_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getLang() <em>Lang</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLang()
   * @generated
   * @ordered
   */
  protected String lang = LANG_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected LanguageStringImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return IRMLPackage.Literals.LANGUAGE_STRING;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getQutoedString()
  {
    return qutoedString;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setQutoedString(String newQutoedString)
  {
    String oldQutoedString = qutoedString;
    qutoedString = newQutoedString;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IRMLPackage.LANGUAGE_STRING__QUTOED_STRING, oldQutoedString, qutoedString));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLang()
  {
    return lang;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLang(String newLang)
  {
    String oldLang = lang;
    lang = newLang;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IRMLPackage.LANGUAGE_STRING__LANG, oldLang, lang));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case IRMLPackage.LANGUAGE_STRING__QUTOED_STRING:
        return getQutoedString();
      case IRMLPackage.LANGUAGE_STRING__LANG:
        return getLang();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case IRMLPackage.LANGUAGE_STRING__QUTOED_STRING:
        setQutoedString((String)newValue);
        return;
      case IRMLPackage.LANGUAGE_STRING__LANG:
        setLang((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case IRMLPackage.LANGUAGE_STRING__QUTOED_STRING:
        setQutoedString(QUTOED_STRING_EDEFAULT);
        return;
      case IRMLPackage.LANGUAGE_STRING__LANG:
        setLang(LANG_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case IRMLPackage.LANGUAGE_STRING__QUTOED_STRING:
        return QUTOED_STRING_EDEFAULT == null ? qutoedString != null : !QUTOED_STRING_EDEFAULT.equals(qutoedString);
      case IRMLPackage.LANGUAGE_STRING__LANG:
        return LANG_EDEFAULT == null ? lang != null : !LANG_EDEFAULT.equals(lang);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (qutoedString: ");
    result.append(qutoedString);
    result.append(", lang: ");
    result.append(lang);
    result.append(')');
    return result.toString();
  }

} //LanguageStringImpl
