/*
 * generated by Xtext 2.20.0
 */
package org.xtext.r2ps.rml;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class RMLRuntimeModule extends AbstractRMLRuntimeModule {
}
