/*
 * generated by Xtext 2.20.0
 */
package org.xtext.r2ps.rml;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class RMLStandaloneSetup extends RMLStandaloneSetupGenerated {

	public static void doSetup() {
		new RMLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
