/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.rml.validation;

import org.xtext.example.rml.validation.AbstractIRMLValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class IRMLValidator extends AbstractIRMLValidator {
}
