/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.rml.ide;

import org.xtext.example.rml.ide.AbstractIRMLIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class IRMLIdeModule extends AbstractIRMLIdeModule {
}
