/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.rml.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.rml.IRMLRuntimeModule;
import org.xtext.example.rml.IRMLStandaloneSetup;
import org.xtext.example.rml.ide.IRMLIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class IRMLIdeSetup extends IRMLStandaloneSetup {
  @Override
  public Injector createInjector() {
    IRMLRuntimeModule _iRMLRuntimeModule = new IRMLRuntimeModule();
    IRMLIdeModule _iRMLIdeModule = new IRMLIdeModule();
    return Guice.createInjector(Modules2.mixin(_iRMLRuntimeModule, _iRMLIdeModule));
  }
}
