/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.rml;

import org.xtext.example.rml.AbstractIRMLRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class IRMLRuntimeModule extends AbstractIRMLRuntimeModule {
}
