/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.rml;

import org.xtext.example.rml.IRMLStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class IRMLStandaloneSetup extends IRMLStandaloneSetupGenerated {
  public static void doSetup() {
    new IRMLStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
