/*
 * generated by Xtext 2.16.0
 */
package org.xtext.example.rml.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.rml.ui.internal.RmlActivator;

public class IRMLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return RmlActivator.getInstance().getInjector("org.xtext.example.rml.IRML");
	}

}
