/*
 * generated by Xtext 2.16.0
 */
package org.xtext.example.rml.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.rml.parser.antlr.internal.InternalIRMLParser;
import org.xtext.example.rml.services.IRMLGrammarAccess;

public class IRMLParser extends AbstractAntlrParser {

	@Inject
	private IRMLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalIRMLParser createParser(XtextTokenStream stream) {
		return new InternalIRMLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Mapping";
	}

	public IRMLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(IRMLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
