/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.rml.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.example.rml.ui.AbstractIRMLUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class IRMLUiModule extends AbstractIRMLUiModule {
  public IRMLUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
