<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="iRML" nsURI="http://www.xtext.org/example/rml/RML" nsPrefix="iRML">
  <eClassifiers xsi:type="ecore:EClass" name="Mapping">
    <eStructuralFeatures xsi:type="ecore:EReference" name="directives" upperBound="-1"
        eType="#//Directive" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="triplesMaps" upperBound="-1"
        eType="#//TriplesMap" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="AbsolutePath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Directive">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prefix" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="iri" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="base" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TriplesMap">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="logicalSource" eType="#//LogicalSource"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subjectMap" upperBound="-1"
        eType="#//SubjectMap" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="predicateObjectMaps" upperBound="-1"
        eType="#//PredicateObjectMap" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dctermsType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LogicalSource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="iterator" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="referenceFormulation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="query" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sqlVersion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tableName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//RMLSource/DataRetrieval"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="table" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubjectMap" eSuperTypes="#//TermMap">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="class" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="graphMaps" upperBound="-1"
        eType="#//GraphMap" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="functionMaps" upperBound="-1"
        eType="#//FunctionTermMap" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="equalConditions" upperBound="-1"
        eType="#//RMLCondition/BooleanCondition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PredicateObjectMap">
    <eStructuralFeatures xsi:type="ecore:EReference" name="predicateMaps" upperBound="-1"
        eType="#//PredicateMap" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="objectMaps" upperBound="-1"
        eType="#//ObjectMap" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refObjectMaps" upperBound="-1"
        eType="#//ReferencingObjectMap" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dctermsType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="graphMaps" upperBound="-1"
        eType="#//GraphMap" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="functionMaps" upperBound="-1"
        eType="#//FunctionTermMap" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ownTriplesMap" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fallbackMaps" upperBound="-1"
        eType="#//PredicateObjectMap" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="equalConditions" upperBound="-1"
        eType="#//RMLCondition/BooleanCondition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bindingConditions" upperBound="-1"
        eType="#//RMLCondition/BindingCondition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectMap" eSuperTypes="#//TermMap">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="objects" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="graphMaps" upperBound="-1"
        eType="#//GraphMap" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentTermMap" eType="#//ParentTermMap"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="functionMaps" upperBound="-1"
        eType="#//FunctionTermMap" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parentTriplesMap" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="joinConditions" upperBound="-1"
        eType="#//JoinCondition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fallbackMaps" upperBound="-1"
        eType="#//ObjectMap" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="equalConditions" upperBound="-1"
        eType="#//RMLCondition/BooleanCondition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bindingConditions" upperBound="-1"
        eType="#//RMLCondition/BindingCondition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="languageMap" eType="#//LanguageMap"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReferencingObjectMap">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parentTriplesMap" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="joinConditions" upperBound="-1"
        eType="#//JoinCondition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fallbackMaps" upperBound="-1"
        eType="#//ReferencingObjectMap" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="graphMaps" upperBound="-1"
        eType="#//GraphMap" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="equalConditions" upperBound="-1"
        eType="#//RMLCondition/BooleanCondition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bindingConditions" upperBound="-1"
        eType="#//RMLCondition/BindingCondition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ownTriplesMap" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PredicateMap" eSuperTypes="#//TermMap">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="predicates" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="graphMaps" upperBound="-1"
        eType="#//GraphMap" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="equalConditions" upperBound="-1"
        eType="#//RMLCondition/BooleanCondition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bindingConditions" upperBound="-1"
        eType="#//RMLCondition/BindingCondition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JoinCondition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parent" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="child" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="functionMaps" upperBound="-1"
        eType="#//FunctionTermMap" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GraphMap" eSuperTypes="#//TermMap">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="graphs" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="functionMaps" upperBound="-1"
        eType="#//FunctionTermMap" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Constant">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Reference">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Template">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TermType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TermMap">
    <eStructuralFeatures xsi:type="ecore:EReference" name="constant" eType="#//Constant"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reference" eType="#//Reference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="template" eType="#//Template"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="datatype" eType="#//DataType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="termtype" eType="#//TermType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inverseExpression" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ownTriplesMap" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="column" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="languageTag" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="languageMap" eType="#//LanguageMap"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CLASS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionTermMap" eSuperTypes="#//TermMap">
    <eStructuralFeatures xsi:type="ecore:EReference" name="logicalSource" eType="#//LogicalSource"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="predicateObjectMaps" upperBound="-1"
        eType="#//PredicateObjectMap" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="functionTriplesMap" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="functionIRI" eType="#//RDFTermType/IRI"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//RDFTermType/IRI" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParentTermMap" eSuperTypes="#//TermMap"/>
  <eClassifiers xsi:type="ecore:EEnum" name="tm">
    <eLiterals name="IRI"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LanguageMap">
    <eStructuralFeatures xsi:type="ecore:EReference" name="reference" eType="#//Reference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constant" eType="#//Constant"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ownTriplesMap" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eSubpackages name="RMLCondition" nsURI="http://rml.io/rmlcondition" nsPrefix="rmlcondition">
    <eClassifiers xsi:type="ecore:EClass" name="BindingCondition" eSuperTypes="#//RMLCondition/Condition">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="variable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BooleanCondition" eSuperTypes="#//RMLCondition/Condition">
      <eStructuralFeatures xsi:type="ecore:EReference" name="fallback" eType="#//PredicateObjectMap"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NegationCondition" eSuperTypes="#//RMLCondition/BooleanCondition"/>
    <eClassifiers xsi:type="ecore:EClass" name="Condition">
      <eStructuralFeatures xsi:type="ecore:EReference" name="reference" eType="#//Reference"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="condition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="refObjMap" eType="#//ReferencingObjectMap"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="nestedCondition" upperBound="-1"
          eType="#//RMLCondition/Condition" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="binding" upperBound="-1"
          eType="#//RMLCondition/BindingCondition" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="functionMaps" upperBound="-1"
          eType="#//FunctionTermMap" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JoinConditionMetric">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="metric" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="RDFTermType" nsURI="http://rml.io/rdftermtype" nsPrefix="rdftermtype">
    <eClassifiers xsi:type="ecore:EClass" name="IRI">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="IRIREF" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="PrefixedName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Literal">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="NumericLiteral" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="BooleanLiteral" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="RDFLiteral" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BlankNode">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="BlankNodeLabel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ANON" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="RMLSource" nsURI="http://rml.io/rmlsource" nsPrefix="rmlsource">
    <eClassifiers xsi:type="ecore:EClass" name="Dataset">
      <eStructuralFeatures xsi:type="ecore:EReference" name="distribution" eType="#//RMLSource/Distribution"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IriTemplate">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="template" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="hydraMapping" upperBound="-1"
          eType="#//RMLSource/HydraMapping" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PagedCollection">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="itemsPerPage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstPage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="nextPage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Database">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="jdbcDSN" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="jdbcDriver" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="username" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="password" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Service">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="endpoint" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="supportedLanguage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="resultFormat" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="csvwTable">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="dialect" eType="#//RMLSource/Dialect"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ProvidedBy">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="localLibrary" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="class" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="method" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Distribution">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="downloadURL" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="HydraMapping">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="variable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="required" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Dialect">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="delimiter" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="encoding" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="header" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="headerRowCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="trim" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DataRetrieval">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="dataset" eType="#//RMLSource/Dataset"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="webAPI" eType="#//RMLSource/IriTemplate"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="pagedCollection" eType="#//RMLSource/PagedCollection"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="database" eType="#//RMLSource/Database"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sparql" eType="#//RMLSource/Service"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="csvonWeb" eType="#//RMLSource/csvwTable"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="distribution" eType="#//RMLSource/Distribution"
          containment="true"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="RMLExtension" nsURI="http://rml.io/rmlextension" nsPrefix="rmlextension"/>
</ecore:EPackage>
