/*
 * generated by Xtext 2.16.0
 */
package org.xtext.example.rml.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.example.rml.ui.internal.RmlActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class IRMLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(RmlActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		RmlActivator activator = RmlActivator.getInstance();
		return activator != null ? activator.getInjector(RmlActivator.ORG_XTEXT_EXAMPLE_RML_IRML) : null;
	}

}
