/*
 * generated by Xtext 2.16.0
 */
package org.xtext.example.rml.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractIRMLScopeProvider extends DelegatingScopeProvider {
}
