/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.rml.ui.contentassist;

import org.xtext.example.rml.ui.contentassist.AbstractIRMLProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class IRMLProposalProvider extends AbstractIRMLProposalProvider {
}
